<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\..\..\..\Temp\BulkyBook\BulkyBook.Business\Services\ApplicationUserService.cs" Link="Services\ApplicationUserService.cs" />
    <Compile Include="..\..\..\..\..\..\Temp\BulkyBook\BulkyBook.Business\Services\IServices\IApplicationUserService.cs" Link="Services\IServices\IApplicationUserService.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BulkyBook.DataAccess\BulkyBook.DataAccess.csproj" />
    <ProjectReference Include="..\BulkyBook.Models\BulkyBook.Models.csproj" />
    <ProjectReference Include="..\BulkyBook.Utility\BulkyBook.Utility.csproj" />
  </ItemGroup>

</Project>
